### ISSUE TITLE
Create Symfony Flex recipe for lib

### ISSUE THREAD

**Issue by igorkamyshev** [QEEP-Pro/QEEPApiClient#1]
[Documentation](https://github.com/symfony/recipes)

**Comment by sivolobov** [comment]
Why closing?

**Comment by igorkamyshev** [comment]
The task has not been touched since November 2017. I guess, nobody want to create this recipe.

Also, PHP ecosystem has changed a lot, now I don't feel like an expert in Symfony and can't review PR with recipe or give some advices.
